### ISSUE TITLE
Error while trying to create Volumes on Defined Pool

### ISSUE THREAD

**Issue by daramosch** [Infinidat/infinisdk#1]
I'm hitting this error while trying to create  volumes in an already defined Pool. Have you seen something similar? 
Traceback (most recent call last):
  File "C:\...\LUN_Creation.py", line 81, in <module>
    vols = system.volumes.create_many(pool=p, name=name, count=vol, size=siz)
  File "C:\Python35\lib\site-packages\infinisdk\infinibox\dataset.py", line 52, in create_many
    for i in range(1, count + 1)]
  File "C:\Python35\lib\site-packages\infinisdk\infinibox\dataset.py", line 52, in <listcomp>
    for i in range(1, count + 1)]
  File "C:\Python35\lib\site-packages\infinisdk\core\type_binder.py", line 148, in create
    return self.object_type.create(self.system, *args, **kwargs)
  File "C:\Python35\lib\site-packages\infinisdk\infinibox\volume.py", line 75, in create
    pool.invalidate_cache('allocated_physical_capacity', 'free_physical_capacity', 'free_virtual_capacity',
AttributeError: 'str' object has no attribute 'invalidate_cache' 

I was able to use the infinisdk for authentication, Pool and Host Creation previously. Even while creating single volume I got the same error. 

>>> system = InfiniBox(ibox, auth=(username,password))
>>> system.login()
<Response [200]>
>>> p = "Storage_Pool"
>>> v = system.volumes.create(pool=p, name='my_vol')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python35\lib\site-packages\infinisdk\core\type_binder.py", line 148, in create
    return self.object_type.create(self.system, *args, **kwargs)
  File "C:\Python35\lib\site-packages\infinisdk\infinibox\volume.py", line 75, in create
    pool.invalidate_cache('allocated_physical_capacity', 'free_physical_capacity', 'free_virtual_capacity',
AttributeError: 'str' object has no attribute 'invalidate_cache'
>>>

**Comment by vmalloc** [comment]
InfiniSDK expects a pool *object* for the `pool` parameter, so assuming you have the pool name as an input your code should look it up first:
```
pool = system.pools.get(name='pool_name')
v = system.volumes.create(pool=pool, ...)
```
Alternatively you can pass the pool *numeric id* as the `pool_id` argument to the volume creation operation.

**Comment by vmalloc** [comment]
Having said that we will consider adding support for this use case, as it is probably useful and saves some hassle. However it will probably not make it to the upcoming release...

**Comment by daramosch** [comment]
@vmalloc Thanks for your quick response, the issue was resolved with your recommendation successfully. THANKS a lot. :)
BTW I really like the Infinidat Hardware, Great Product! and the infinisdk for automation.

**Comment by vmalloc** [comment]
@daramosch glad you like it! Thanks for the kind feedback!
