### ISSUE TITLE
Best way to create Disconnected Hosts List

### ISSUE THREAD

**Issue by daramosch** [Infinidat/infinisdk#10]
Hi! 

I was going over the host fields (SAN_Type), is there any way to query from the system all the hosts that are in a disconnected status + any host with one or more disconnected Ports (wwns) ?

**Comment by ayalash** [comment]
Hi @daramosch, 
There is no single query for checking it, but you can do it in 2 phases.
`system.initiators` is the collection for all the ports which are connected to the system, regardless if they are mapped or not.
You can aggregate the addresses of the connected initiators and check you host against it. For example:
```
>>> connected_addresses = set(initiator.get_address() for initiator in system.initiators)
>>> for host in system.hosts:
...     for port in host.get_ports():
...         if port in connected_addresses:
...             continue
...         print(f"Host {host} has disconnected port {port!r}")
```

**Comment by daramosch** [comment]
Thanks Ayalash, This would be very helpful. Now a quick question regarding this. In case of LPAR NPIV Hosts which would have 4 ports (2 active / 2 Inactive) I would need to filter these. I was wondering there is no way to filter them by the host status? 

So in this case I would get the Host reported for the 2 Ports disconnected even though the Resiliency state is connected as it still have 2 ports active. 

Want it to verify with you if there is method to get the Resiliency state from the server directly instead of the port. If not it is ok I'll add a few more lines to filter them, just want it to check if that is a possibility

**Comment by ayalash** [comment]
@daramosch There is no resiliency state method from the server (Infinibox's REST API).

**Comment by daramosch** [comment]
@ayalash Thanks!
