### ISSUE TITLE
Filtering wildcard support

### ISSUE THREAD

**Issue by shorbachuk** [Infinidat/infinisdk#7]
Does the Infinibox API support wildcards?

I want to do something like this ?name=:like*vdi

I want to match stevevdi and not stevevdisteve

**Comment by ayalash** [comment]
@shorbachuk The Infinibox API currently does not support wildcards.
When you use the like operator, it already search for substring, so you don't have to use the `*`, But you cannot use wildcards/regex expressions.

**Comment by ayalash** [comment]
I will pass your request to our product team.
