### ISSUE TITLE
Sort pools by free space

### ISSUE THREAD

**Issue by shorbachuk** [Infinidat/infinisdk#8]
I would like to sort pools objects at the API level. 

HTTP GET: api/rest/pools?sort=-free_virtual_space

Returns this:
`{
    "result": null,
    "error": {
        "code": "UNSUPPORTED_FIELD",
        "message": "The request contains an unsupported field ('free_virtual_space')",
        "reasons": [],
        "severity": "ERROR",
        "is_remote": false,
        "data": null
    },
    "metadata": {
        "ready": true
    }
}`

**Comment by ayalash** [comment]
@shorbachuk The reason for the failure is written in the code of the error - In your case "UNSUPPORTED_FIELD".
Infinibox API support sorting by subset of the fields the collection has - `free_virtual_space` is not one of them.
In infinisdk, you can check if you can sort by the field by checking the field's `is_sortable` parameter.
