### ISSUE TITLE
What is the proper way to enable certificate validation?

### ISSUE THREAD

**Issue by scottfuhrman** [Infinidat/infinisdk#9]
Hello,

We are using the python InfiniSDK and connecting with  use_ssl=True.

The following warnings are received from urllib3.  What is the proper way to enable certificate validation?

/opt/infiniglue/venv/lib/python2.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

Thanks,

Scott

**Comment by ayalash** [comment]
@scottfuhrman When you create the InfiniBox object, you shouild pass the `ssl_cert` in addition to `use_ssl=True`. For example:
```
>>> from infinisdk import InfiniBox
>>> system = InfiniBox('ibox610', use_ssl=True, ssl_cert="my cert")
```
Your `ssl_cert` should be according to requests package `cert` parameter:
> SSL client certificate default, if String, path to ssl client
cert file (.pem). If Tuple, ('cert', 'key') pair.

https://requests.kennethreitz.org/en/master/user/advanced/#client-side-certificates
